<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <Platform>x64</Platform>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>mu3-monitor</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\references\Mu3IO.NET\Source\MU3IO.csproj" />
  </ItemGroup>
</Project>
